name: Build, Scan Node App with Trivy, and Push to Docker Hub

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Node app Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          sudo mv trivy /usr/local/bin/

      - name: Scan Dockerfile for misconfigurations (Trivy config)
        run: |
          trivy config Dockerfile --severity CRITICAL,HIGH --exit-code 1 --format table

      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest

      - name: Push Docker image (only if scan passed)
        if: success()
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
