name: Build, Scan, and Push

on:
  push:
    branches: [main]

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Scan Dockerfile for misconfigurations
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            bitnami/trivy:latest \
            config /workspace/Dockerfile.secured --exit-code 1

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/node-app:latest .

      - name: Push Docker image
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/node-app:latest
